
name: Run Semantic release
on:
  push:
    branches:
      - master

env:
  NODE_ENV: test
jobs:
  main_workflow:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - uses: actions/checkout@v2
      # Setup the node environment
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 14
      # Cache dependencies
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      # Install dependencies
      - run: npm ci --prefer-offline
      - run: npx semantic-release
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.GH_PAT_SEMANTIC_RELEASE }}
